Split LRU list
Open-CAS/ocf pull request #429
Opened 2020-12-09 13:41 UTC by arutk

2020-12-11 15:31 UTC, robertbaldyga requested changes

2020-12-11 15:31 UTC, robertbaldyga commented on src/eviction/lru.c
> +	uint32_t start_evp, bool clean, struct ocf_lru_iter *iter)
As a convention constructor takes pointer to initialized object as a first parameter.

2020-12-11 15:31 UTC, robertbaldyga commented on src/eviction/lru.c
> +	dirty_list = &part->runtime->eviction[ev_list].policy.lru.dirty;
`evp_get_list()` could be used instead.

2020-12-11 15:31 UTC, robertbaldyga commented on src/eviction/lru.c
> +	dirty_list = &part->runtime->eviction[ev_list].policy.lru.dirty;
`evp_get_list()` could be used instead.

2020-12-16 08:03 UTC, mmichal10 commented on src/metadata/metadata_partition_structs.h
> +	unsigned id;
You can use `ocf_part_id_t` instead of unsigned

2020-12-16 22:55 UTC, robertbaldyga approved these changes

2020-12-17 12:12 UTC, Ostrokrzew approved these changes

2020-12-17 15:15 UTC, mmichal10 approved these changes

2020-12-18 10:20 UTC, Ostrokrzew approved these changes

2020-12-18 16:05 UTC, merged