Create template for issues
Open-CAS/ocf pull request #444
Opened 2021-01-26 09:47 UTC by Ostrokrzew

Signed-off-by: Slawomir Jankowski <slawomir.jankowski@intel.com>

2021-02-02 17:07 UTC, rafalste approved these changes

2021-02-15 17:18 UTC, robertbaldyga requested changes

2021-02-15 17:18 UTC, robertbaldyga commented on .github/ISSUE_TEMPLATE/bug.md
> +* Adapter configuration:
Why is that named "Adapter configuration"? Why not just "Configuration"?

2021-02-16 10:57 UTC, rafalste approved these changes

2021-02-25 19:04 UTC, robertbaldyga approved these changes

2021-02-25 19:04 UTC, merged