Cacheline alignment
Open-CAS/ocf pull request #476
Opened 2021-03-22 07:20 UTC by mmkayPL

2021-03-24 10:53 UTC, Ostrokrzew approved these changes

2021-03-25 17:32 UTC, arutk commented
retest this please

2021-03-25 18:21 UTC, robertbaldyga approved these changes

2021-03-25 18:22 UTC, robertbaldyga commented
restest this please

2021-03-25 18:55 UTC, robertbaldyga submitted a review, later dismissed
Please update pyocf wrappers accordingly.

2021-03-26 09:18 UTC, arutk requested changes

2021-03-26 10:16 UTC, arutk approved these changes

2021-03-26 10:32 UTC, jfckm approved these changes

2021-03-26 11:01 UTC, merged