Add priv field initialization on cache start
Open-CAS/ocf pull request #506
Opened 2021-05-25 14:06 UTC by jfckm

This allows access to it in ctx_metadata_updater_init, which is
done in the same call stack during initalization.

Signed-off-by: Kozlowski Mateusz <mateusz.kozlowski@intel.com>

2021-05-25 22:14 UTC, robertbaldyga requested changes
Please update examples, pyocf and tests.

2021-05-26 06:18 UTC, mmkayPL approved these changes

2021-05-26 07:50 UTC, arutk approved these changes

2021-05-26 08:28 UTC, robertbaldyga approved these changes

2021-05-26 08:31 UTC, merged