Rm metadata updater
Open-CAS/ocf pull request #509
Opened 2021-06-01 11:38 UTC by mmkayPL

2021-06-02 10:13 UTC, arutk approved these changes

2021-06-02 10:13 UTC, arutk commented on src/utils/utils_alock.c
> +#define _WAITERS_LIST_ITEM(cache_line) ((cache_line) % _WAITERS_LIST_ENTRIES)
"entry' would be better than "cache_line" here

2021-06-02 10:14 UTC, arutk requested changes
> *[Reviewable](https://reviewable.io/reviews/open-cas/ocf/509)* status: 0 of 2 LGTMs obtained

___
*[tests/unit/tests/concurrency/ocf_cache_line_concurrency.c/ocf_cache_line_concurrency.c, line 372 at r2](https://reviewable.io/reviews/open-cas/ocf/509#-MbBBe2p0n07iyhUE7uE:-MbBBe2q2WEVL3hMclSA:bgby002) ([raw file](https://github.com/open-cas/ocf/blob/b5d4ab07ea4b6b4579556b824bbc9b50c69aa3a4/tests/unit/tests/concurrency/ocf_cache_line_concurrency.c/ocf_cache_line_concurrency.c#L372)):*
> ```C
> 	{
> 		rw = rand() % 2;
> 		single = (rand() % 4 == 0);
> ```

let's make it %5 rather than %4 to make generate wider range of rw/single combinations.


<!-- Sent from Reviewable.io -->

2021-06-02 11:41 UTC, arutk commented on src/utils/utils_alock.c
> +			}
I think Michał is right, but there are some extra considerations - please double check them before adding a break here. One request may lock multiple cachelines resolving to the same 'idx' value. So there might be multiple waiter entries for a single request on a sinble list. The way we currently use this function assures that it is called once for each locked/waiting entry, so breaking early will yield some work to the next call. 

So I guess it boils down to how we define this function API.

2021-06-02 12:32 UTC, arutk requested changes, later dismissed

2021-06-02 12:32 UTC, arutk commented on src/ocf_request.h
> +	uint8_t __alock_entry_map[0];
I think this isn't/shouldn't be used anywhere

2021-06-09 09:33 UTC, KamilLepek commented
retest this please

2021-06-09 11:32 UTC, ArkadiuszNeumann commented
retest this please

2021-06-09 14:04 UTC, ArkadiuszNeumann commented
retest this please

2021-06-09 14:39 UTC, ArkadiuszNeumann commented
retest this please

2021-06-09 14:53 UTC, ArkadiuszNeumann commented
retest this please

2021-06-09 14:56 UTC, ArkadiuszNeumann commented
retest this please

2021-06-10 08:02 UTC, ArkadiuszNeumann commented
retest this please

2021-06-10 09:40 UTC, ArkadiuszNeumann commented
retest this please

2021-06-16 10:07 UTC, robertbaldyga requested changes

2021-06-16 10:07 UTC, robertbaldyga commented on src/utils/utils_alock.h
> +	ocf_cl_lock_slow lock_lines_slow;
I think that `lock_entries_*` would be better, as the locked entries are not always cache lines. This also applies to naming convention in entire mio concurrency.

2021-06-16 11:43 UTC, robertbaldyga approved these changes

2021-06-16 15:06 UTC, rafalste approved these changes

2021-06-17 07:34 UTC, merged