Add back fastpath
Open-CAS/ocf pull request #540
Opened 2021-07-20 08:01 UTC by mmkayPL

Signed-off-by: Kozlowski Mateusz <mateusz.kozlowski@intel.com>

2021-07-20 13:07 UTC, robertbaldyga requested changes

2021-07-20 13:07 UTC, robertbaldyga commented on src/ocf_core.c
> +	ocf_resolve_effective_cache_mode(cache, core, req);
This is rather expensive, because it performs seq_cutoff check. Maybe fast path could restore original cache mode on fail?

2021-07-20 13:07 UTC, robertbaldyga commented on src/ocf_core.c
> +		ocf_req_dealloc_map(req);
This is not necessary. `ocf_io_put()` will call `ocf_req_put()` which will free the map.

2021-07-20 14:57 UTC, robertbaldyga approved these changes

2021-07-21 06:25 UTC, robertbaldyga approved these changes

2021-07-21 11:18 UTC, rafalste approved these changes

2021-07-21 12:58 UTC, merged