Fix attach with no cache_line_size specified
Open-CAS/ocf pull request #570
Opened 2021-09-10 12:48 UTC by jfckm

Fixes #564 
Signed-off-by: Jan Musial <jan.musial@intel.com>

2021-09-10 14:11 UTC, rafalste submitted a review, later dismissed

2021-09-10 14:57 UTC, robertbaldyga commented on src/mngt/ocf_mngt_cache.c
> +	context->metadata.line_size = context->cfg.cache_line_size ?:
In activate path it actually should not be taken from cfg in any case.

2021-09-13 20:15 UTC, robertbaldyga requested changes

2021-09-13 20:15 UTC, robertbaldyga commented on src/mngt/ocf_mngt_cache.c
> +				"forbidden.");
This check is already done bind, so no need for doing it there.

2021-09-14 18:52 UTC, robertbaldyga approved these changes

2021-09-15 15:21 UTC, arutk approved these changes

2021-09-16 17:12 UTC, merged