Introduce flapping of metadata config sections
Open-CAS/ocf pull request #603
Opened 2021-12-09 22:09 UTC by robertbaldyga

This feature provides double buffering of config sections to prevent
situation when power failure during metadata flush leads to partially
updated metadata. Flapping mechanism makes it always possible to perform
graceful rollback to previous config metadata content in such situation.

Signed-off-by: Robert Baldyga <robert.baldyga@intel.com>

2021-12-14 12:49 UTC, mmichal10 submitted a review, later dismissed

2021-12-15 12:07 UTC, arutk requested changes

2021-12-15 12:07 UTC, arutk commented on src/metadata/metadata_superblock.c
> +	sb_config->flapping_idx = (sb_config->flapping_idx + 1) % 2;
... or even better flipped only after config sections are flushed successfully - need to use the negative of flapping_idx in flush function in this case.

2021-12-15 12:11 UTC, arutk commented on src/metadata/metadata_superblock.c
> +	sb_config->flapping_idx = (sb_config->flapping_idx + 1) % 2;
... actually the best place to flip would be at the very end of the pipeline - this way regardless of errors in subsequent management operations the last valid version on drive will never be overwritten until another management operation ends in success.

2021-12-15 12:16 UTC, arutk commented on src/metadata/metadata_superblock.c
> +	sb_config->flapping_idx = (sb_config->flapping_idx + 1) % 2;
... and then restored to the previous value in case of supreblock flush

2021-12-15 15:42 UTC, arutk approved these changes

2021-12-15 16:00 UTC, mmichal10 approved these changes

2021-12-15 16:11 UTC, merged